# Generated by Django 4.2.10 on 2024-03-14 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a10app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportfile',
            old_name='feed',
            new_name='report',
        ),
    ]
