# Generated by Django 4.2.10 on 2024-03-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a10app', '0002_rename_feed_reportfile_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfile',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
