# Generated by Django 4.2.10 on 2024-03-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a10app', '0004_report_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='urgency',
            field=models.IntegerField(default=1),
        ),
    ]
