# Generated by Django 4.2.10 on 2024-03-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a10app', '0008_auto_20240316_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfile',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
