# Generated by Django 4.2.10 on 2024-03-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a10app', '0009_reportfile_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
