# Generated by Django 4.2.10 on 2024-03-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a10app', '0010_report_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='admin_comments',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
