# Generated by Django 4.2.10 on 2024-03-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a10app', '0011_report_admin_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reviewed',
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(default='New', max_length=50),
        ),
    ]
