# Generated by Django 4.2.10 on 2024-04-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a10app', '0012_remove_report_reviewed_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='location',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
