# Generated by Django 4.2.10 on 2024-04-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a10app', '0015_alter_report_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='downvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
