# Generated by Django 4.2.10 on 2024-04-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a10app', '0015_alter_report_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='user_comments',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
