# Generated by Django 4.2.10 on 2024-04-14 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a10app', '0017_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user_comments',
        ),
    ]
